### PR TITLE
CI/CD for Future-MC 1.15.2

### PR DESCRIPTION
**Pull request by Macleykun**
This pull will make it possible to create the Future-MC jar for each commit.

To trigger a deployment to the Releases tab, simply start your commit with Release. The following word will be denoted as the version. Words after the second word aren't a problem for this CI/CD.

Don't fill in the comment field for this pull, as this will screw up the CI/CD releases :P heh.
image
(So the field under Update README.md (#1) should be empty if you want to make a Release here.

Also, i've done a bit of testing and found out you can also let this run on a pullrequest if you want!
Example:
https://github.com/Macleykun/Future-MC/pull/1

Even if users decide to make a commit called Release v1.1.1 it will never trigger :) so a bit of a security is also in place!

Let me know if you wish to have this CI/CD work on pull requests aswell!

### CODE REVIEW

**Comment by Macleykun** [comment]
Any reason why you didn't wanted to merge this one yet?

**Comment by thedarkcolour** [comment]
I don't have 1.15.2 fully committed yet

**Comment by Macleykun** [comment]
Aaah Ok. But why not merge this now? It only adds build artifacts and an indication if the project compiles.

**Comment by thedarkcolour** [comment]
It was a pain in the ass to merge the last one for unrelated reasons

**Pull request merged**
