### PR TITLE
Add enchantment descriptions

### PR DESCRIPTION
**Pull request by Hogan-Dazs**
For use with DarkhaxDev's enchantment description system

### CODE REVIEW

**Comment by thedarkcolour** [comment]
Change the 'minecraftfuture' to 'futuremc'

**Comment by Hogan-Dazs** [comment]
Those are the localization keys that Enchantment Descriptions/WAWLA looks for, based on the modID. I verified that this works, I don't think it would work if I changed it.

**Comment by thedarkcolour** [comment]
The modid has changed to futuremc. Please change it

**Comment by thedarkcolour** [comment]
Thanks!

**Comment by thedarkcolour** [comment]
I'll merge this in 0.2.03

**Comment by thedarkcolour** [comment]
The contents of this pull request are no longer in Future MC. I have replaced them with my own.

**Pull request merged**
