### PR TITLE
Implemented IPlantable for BlockBerryBush/ItemBerry.

### PR DESCRIPTION
**Pull request by stfwi**
Hi tdc, I have a proposal implementation for Forge IPlantable interface for the Berries, which came up in 
a related issue here: https://github.com/stfwi/engineers-decor/issues/75.
Could you take a look if this is acceptable? Cheers, wile -

### CODE REVIEW

**Comment by thedarkcolour** [comment]
It actually isn't suitable because I'm switching to Kotlin, but I'll make sure to implement it in the next update.

**Comment by thedarkcolour** [comment]
I'll update the repo shortly.

**Comment by thedarkcolour** [comment]
Turns out that IPlantable is already implemented in BlockBush, so there's nothing to implement.

**Comment by stfwi** [comment]
Out of my head I am not sure there. The berries and the bush are not visibly linked to another (as for block-items). So it may be needed to add IPlantable to the berries to define that it can be planted to a bush. Other mods only see the item as such and probably do not know that. They also cannot obtain the block for testing IPlantable in the block.
It may be worth double checking.

**Comment by thedarkcolour** [comment]
I'll try that

**Comment by thedarkcolour** [comment]
Can you check my latest commit? My mod doesn't compile at the moment.

**Comment by stfwi** [comment]
Sure that, I'll check this evening and give feedback.

**Comment by stfwi** [comment]
Aye, the berry item looks good. Thanks again taking this on and implementing! Cheers -

**Pull request closed without merging**
